# web-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: participant-b-web
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: participant-b-web
  template:
    metadata:
      labels:
        app: participant-b-web
    spec:
      containers:
      - name: participant-b-web
        image: noah/participant-b
        imagePullPolicy: Never
        ports:
        - containerPort: 9096
          name: par-b-web-port
        env:
          - name: POSTGRES_DB
            value: db_b
          - name: POSTGRES_USER
            value: username_b
          - name: POSTGRES_PASSWORD
            value: password_b
        #resources:
        #  limits:
        #    memory: 250M
        #    cpu: 500m
---
# web-service.yml
apiVersion: v1
kind: Service
metadata:
  name: participant-b-web-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: participant-b-web
  ports:
  - name: par-b-web-port
    port: 9982 # porta esterna del servizio in Docker
    targetPort: 9096 # porta interna del servizio in Docker
    nodePort: 30982 # porta esterna del cluster in Kubernetes (l'unica esposta su localhost)
